name: Deploy

on:
  push:
    branches:
      - main  # Adjust the branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh user@your-vps-ip << 'EOF'
        cd /path/to/your-app
        git pull origin main
        npm install
        npm run build
        pm2 restart your-app
        EOF
