name: Feature Branch Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test-db:
        image: postgres:15
        ports:
          - 5434:5432
        env:
          DATABASE_TEST_URL: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        volumes:
          - ./sql:/docker-entrypoint-initdb.d/

    steps:
      # Step 1: Check out the co de
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Use Specific Yarn Version
        run: corepack prepare yarn@4.4.0 --activate

      # Step 2: Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 3: Wait for PostgreSQL
      - name: Wait for PostgreSQL
        run: |
          until nc -z localhost 5432; do
            echo "Waiting for database..."
            sleep 2
          done
          echo "Database is ready!"

      # Step 4: Run test
      - name: Run tests
        env:
          HTTP_BASIC_USER: ${{ secrets.HTTP_BASIC_USER }}
          HTTP_BASIC_PASS: ${{ secrets.HTTP_BASIC_PASS }}
          DATABASE_TEST_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@5.253.188.129:5434/${{ secrets.POSTGRES_DB }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: yarn test
