name: Feature Branch Tests

on:
  push:
    branches:
      - '**' # Runs on all branches except main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and Corepack
      - name: Set up Node.js and Corepack
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Use Specific Yarn Version
        run: corepack prepare yarn$4.4.0 --activate

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Run tests
      - name: Run tests
        run: yarn test